#!/usr/bin/env python3
# coding: utf-8
import os
import sys
from getpass import getpass
import keyring
from twins import Twins

def get_username ():
    try:
        username = open(os.path.expanduser("~/.twins-username")).read()
    except IOError:
        username = input("enter username: ")
        with open(os.path.expanduser("~/.twins-username"), "w") as f: f.write(username)
    return username


def get_passwd (username):
    """ OS X のキーリングがよくわからないので、ホームディレクトリに0600なファイルを作る。"""
    try:
        passwd = open(os.path.expanduser("~/.twins-passwd")).read()
    except IOError:
        passwd = getpass("enter passwd: ")
        # XXX
        open(os.path.expanduser("~/.twins-passwd"), "w").close()
        os.chmod(os.path.expanduser("~/.twins-passwd"), 0o600)
        with open(os.path.expanduser("~/.twins-passwd"), "w") as f:
            f.write(passwd)
    return passwd

def delete_account_info (username):
    try:
        os.remove(os.path.expanduser("~/.twins-username"))
        os.remove(os.path.expanduser("~/.twins-passwd"))
    except:
        pass

HELP = """
Usage: univ command

commands:
  t - 成績開示
"""

def main ():
    try:
        command = sys.argv[1]
    except IndexError:
        sys.exit(HELP)

    if command == "t":
        t = Twins(get_username(), get_passwd(get_username()))
        print("評価\t単位数\t科目名")
        for a in t.get_achievements():
            try:
                print("%s\t%s\t%s" % (a["総合評価"], a["単位数"], a["科目名"]))
            except KeyError:
                pass # FIXME: 謎の空リスト対策。たぶんCSVの最後に要らない改行が入ってる。
    elif command == "d":
        # イースターエッグ: 落単リスト。リフレッシュマンなんていないので考慮してない。
        t = Twins(get_username(), get_passwd(get_username()))
        print("単位数\t科目名")
        i=0
        for a in t.get_achievements():
            try:
                if a["総合評価"] != "D": continue
                i += float(a["単位数"])
                print("%s\t%s" % (a["単位数"], a["科目名"]))
            except KeyError:
                pass # FIXME: 謎の空リスト対策。たぶんCSVの最後に要らない改行が入ってる。
        if i > 15: print("がんばろう")
    else:
        sys.exit(HELP)

if __name__== "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit("aborted.")
